name: Build frp for armv5tel

on:
  release:
    types: [ published ]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag'
        required: true
        default: 'test'
permissions:
  contents: read


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        repository: fatedier/frp
        ref: main # 可以指定分支或标签

    - name: Set up Docker for ARM cross-compilation
      uses: docker/setup-buildx-action@v2
      with:
        version: latest

    - name: Build FRP for ARM
      run: |
        # Create a Dockerfile on-the-fly
        echo '
        FROM golang:1.20 AS build

        ENV GOARCH=arm
        ENV GOARM=5
        ENV CGO_ENABLED=0

        WORKDIR /app
        COPY . .

        RUN go mod download
        RUN make

        FROM scratch
        COPY --from=build /app/bin/frps /frps
        COPY --from=build /app/bin/frpc /frpc

        ENTRYPOINT ["/frps"]
        ' > Dockerfile.arm

        # Build the Docker image for ARM
        docker buildx create --use
        docker buildx build --platform linux/arm/v5 --tag frp-arm -f Dockerfile.arm .

    - name: Run tests
      run: |
        # Example of running tests within the Docker container
        docker run --rm frp-arm make gotest

    - name: Clean up
      run: |
        docker system prune -f



