name: Build yuze for ARMv5

on:
  workflow_dispatch:  # 手动触发
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v3

    - name: Checkout yuze repository
      uses: actions/checkout@v3
      with:
        repository: P001water/yuze  # 指定仓库
        path: yuze  # 克隆到yuze目录

    - name: Set up ARM toolchain
      run: sudo apt-get install -y gcc-arm-linux-gnueabi

    - name: Compile yuze
      run: |
        cd yuze
        ls -al
        arm-linux-gnueabi-gcc -o yuze *.c

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: yuze-armv5
        path: yuze/yuze
