name: Build frp for armv5tel

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag'
        required: true
        default: 'test'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        repository: fatedier/frp
        ref: v0.54.0  # 确保这个分支存在，或者使用合适的分支名

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Create Dockerfile for ARM
      run: |
        echo '
        FROM golang:1.20 AS build

        ENV GOARCH=arm
        ENV GOARM=5
        ENV CGO_ENABLED=0

        WORKDIR /app
        COPY . .

        RUN go mod download
        RUN CGO_ENABLED=0 GOOS=linux GOARCH=arm GOARM=5 go build -ldflags="-w -s" -o /app/bin/frps ./cmd/frps
        RUN CGO_ENABLED=0 GOOS=linux GOARCH=arm GOARM=5 go build -ldflags="-w -s" -o /app/bin/frpc ./cmd/frpc

        FROM scratch
        COPY --from=build /app/bin/frps /frps
        COPY --from=build /app/bin/frpc /frpc

        ENTRYPOINT ["/frps"]
        ' > Dockerfile.arm

    - name: Build Docker image for ARM
      run: |
        docker buildx create --use
        docker buildx build --platform linux/arm/v5 --tag frp-arm:${{ github.event.inputs.tag }} -f Dockerfile.arm .

    - name: List files after build
      run: |
        docker run --rm --platform linux/arm/v5 frp-arm:${{ github.event.inputs.tag }} ls -al /app/bin

    - name: Compress binaries with UPX
      run: |
        docker run --rm --platform linux/arm/v5 frp-arm:${{ github.event.inputs.tag }} upx --best --lzma /frps /frpc

    - name: Clean up
      run: |
        docker system prune -f
