name: Build frp for armv5tel

on:
  release:
    types: [ published ]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag'
        required: true
        default: 'test'
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: Janit8r/frp-2
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'  # Ensure this is the Go version you need

      - name: Build FRP for ARM
        run: |
          export GOARCH=arm
          export GOARM=5
          export CC=arm-linux-gnueabi-gcc
          export CGO_ENABLED=1

          # Navigate to the repository directory
          cd frp

          # Ensure Go modules are up-to-date
          go mod tidy

          # Clean any previous builds
          make clean

          # Build frpc and frps
          make frpc frps
        env:
          GOROOT: /opt/hostedtoolcache/go/1.20/x64  # Ensure this matches the Go version
          GOFLAGS: -tags frpc

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: frp-build
          path: frp/bin/


