name: Build frp for armv5tel

on:
  release:
    types: [ published ]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag'
        required: true
        default: 'test'
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout frp code from GitHub
      uses: actions/checkout@v3
      with:
        repository: fatedier/frp
        ref: master  # 你可以选择特定的分支或标签
        path: frp  # 将代码放在 'frp' 目录下

    - name: Set up Go environment
      uses: actions/setup-go@v4
      with:
        go-version: 1.20  # 确保使用合适的 Go 版本

    - name: Install armv5tel cross-compiler
      run: sudo apt-get install -y gcc-arm-linux-gnueabi

    - name: Build frp for armv5tel
      run: |
        export GOARCH=arm
        export GOARM=5
        export CC=arm-linux-gnueabi-gcc
        export CGO_ENABLED=1

        cd frp
        make clean
        make frpc frps
      env:
        GOFLAGS: "-tags frpc"

    - name: Upload compiled binaries
      uses: actions/upload-artifact@v3
      with:
        name: frp-armv5tel
        path: |
          frp/bin/frpc
          frp/bin/frps
