name: Build frp for armv5tel

on:
  release:
    types: [ published ]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag'
        required: true
        default: 'test'
permissions:
  contents: read


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        version: latest

    - name: Create Dockerfile for ARM
      run: |
        echo '
        FROM golang:1.22 AS build

        ENV GOARCH=arm
        ENV GOARM=5
        ENV CGO_ENABLED=0

        WORKDIR /app
        COPY . .

        RUN go mod download
        RUN make

        FROM scratch
        COPY --from=build /app/bin/frps /frps
        COPY --from=build /app/bin/frpc /frpc

        ENTRYPOINT ["/frps"]
        ' > Dockerfile.arm

    - name: Build Docker image for ARM
      run: |
        docker buildx create --use
        docker buildx build --platform linux/arm/v5 --tag frp-arm --file Dockerfile.arm .

    - name: Run tests inside Docker container
      run: |
        docker run --rm frp-arm make gotest

    - name: Clean up
      run: |
        docker system prune -f



