name: Build and Install Dependencies on CentOS 7

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker container with CentOS 7
        run: |
          # 拉取 CentOS 7 Docker 镜像并启动容器
          docker pull centos:7
          docker run --name centos7-build -d centos:7 sleep infinity

      - name: Configure YUM repositories in CentOS 7
        run: |
          docker exec centos7-build bash -c "
            # 下载阿里云 YUM 源
            curl -o /etc/yum.repos.d/CentOS-Base.repo https://mirrors.aliyun.com/repo/Centos-7.repo &&
            # 更新 YUM 缓存
            yum clean all
          "

      - name: Install Dependencies in CentOS 7
        run: |
          docker exec centos7-build bash -c "
            # 删除现有的 SCL 配置文件
            rm -f /etc/yum.repos.d/CentOS-SCLo-scl.repo &&
            # 配置 YUM 源为阿里云镜像
            echo '[centos-sclo-rh]
            name=CentOS SCLo rh
            baseurl=https://mirrors.aliyun.com/centos/7/sclo/x86_64/rh/
            enabled=1
            gpgcheck=0

            [centos-sclo-scl]
            name=CentOS SCLo scl
            baseurl=https://mirrors.aliyun.com/centos/7/sclo/x86_64/scl/
            enabled=1
            gpgcheck=0' > /etc/yum.repos.d/CentOS-SCLo-scl.repo &&
            # 清除缓存并安装依赖
            yum clean all &&
            yum makecache &&
            yum install -y epel-release &&
            yum install -y gcc gcc-c++ make automake cmake libtool autoconf wget
          "


      - name: Copy Source Code to CentOS 7 Container
        run: |
          docker cp . centos7-build:/src

      - name: Download and Unzip Source Code
        run: |
          docker exec centos7-build bash -c "
            cd /src &&
            curl -L -o testformycode.zip https://raw.githubusercontent.com/tjbcc0/tetmc/refs/heads/main/testformycode.zip &&
            unzip testformycode.zip
          "

      - name: Build Project
        run: |
          docker exec centos7-build bash -c "
            cd /src/testformycode/scripts &&
            chmod 777 *.sh &&
            ./build_deps.sh &&
            cd .. &&
            mkdir build &&
            cd build &&
            cmake -DXMRIG_DEPS=scripts/deps -DBUILD_SHARED_LIBS=OFF .. &&
            make
          "

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: ./testformycode/build  # 修改为你希望上传的文件路径

      - name: Clean up Docker container
        run: |
          docker stop centos7-build
          docker rm centos7-build
