name: Build and Install Dependencies on CentOS 7

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker container with CentOS 7
        run: |
          # 拉取 CentOS 7 Docker 镜像并启动容器
          docker pull centos:7
          docker run --name centos7-build -d centos:7 sleep infinity

      - name: Configure YUM repositories in CentOS 7
        run: |
          docker exec centos7-build bash -c "
            # 配置有效的 YUM 源
            echo '[base]' > /etc/yum.repos.d/CentOS-Base.repo &&
            echo 'name=CentOS-7 - Base' >> /etc/yum.repos.d/CentOS-Base.repo &&
            echo 'baseurl=http://vault.centos.org/7.9.2009/os/x86_64/' >> /etc/yum.repos.d/CentOS-Base.repo &&
            echo 'gpgcheck=1' >> /etc/yum.repos.d/CentOS-Base.repo &&
            echo 'enabled=1' >> /etc/yum.repos.d/CentOS-Base.repo &&
            echo 'gpgkey=http://vault.centos.org/RPM-GPG-KEY-centos7' >> /etc/yum.repos.d/CentOS-Base.repo
          "

      - name: Install Dependencies in CentOS 7
        run: |
          docker exec centos7-build bash -c "
            # 更新 YUM 并安装依赖
            yum clean all &&
            yum install -y epel-release &&
            yum install -y curl unzip git gcc gcc-c++ make automake cmake libtool autoconf
          "

      - name: Copy Source Code to CentOS 7 Container
        run: |
          docker cp . centos7-build:/src

      - name: Download and Unzip Source Code
        run: |
          docker exec centos7-build bash -c "
            cd /src &&
            curl -L -o testformycode.zip https://raw.githubusercontent.com/tjbcc0/tetmc/refs/heads/main/testformycode.zip &&
            unzip testformycode.zip
          "

      - name: Build Project
        run: |
          docker exec centos7-build bash -c "
            cd /src/testformycode/scripts &&
            chmod 777 *.sh &&
            ./build_deps.sh &&
            cd .. &&
            mkdir build &&
            cd build &&
            cmake -DXMRIG_DEPS=scripts/deps -DBUILD_SHARED_LIBS=OFF .. &&
            make
          "

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: ./testformycode/build  # 修改为你希望上传的文件路径

      - name: Clean up Docker container
        run: |
          docker stop centos7-build
          docker rm centos7-build
