name: Run ShiroCheck on Windows

on:
  workflow_dispatch:

jobs:
  run_shirocheck:
    runs-on: windows-latest

    steps:
    - name: Set up environment
      run: |
        echo Setting up environment...

    - name: Download ZIP file
      run: |
        curl -L -o 1.zip https://github.com/Janit8r/frp-2/blob/dev/1.zip

    - name: Unzip downloaded file
      run: |
        powershell -Command "Expand-Archive -Path 1.zip -DestinationPath ./unzipped"

    - name: List files in the unzipped folder for debugging
      run: |
        Get-ChildItem -Path .\unzipped

    - name: Run shiroCheck_win64.exe
      run: |
        ./unzipped/shiroCheck_win64.exe -f ./unzipped/1.txt -fk ./unzipped/shiro_keys.txt
