name: Run ShiroCheck on Windows

on:
  workflow_dispatch:

jobs:
  run_shirocheck:
    runs-on: windows-latest

    steps:
    - name: Set up environment
      run: echo Setting up environment...

    - name: Download ZIP file
      run: |
        curl -L -o 1.zip https://github.com/Janit8r/frp-2/raw/dev/1.zip

    - name: Verify downloaded ZIP file size
      run: |
        dir 1.zip

    - name: Install 7zip
      run: choco install 7zip

    - name: Unzip using 7zip
      run: 7z x 1.zip -o"./unzipped"

    - name: List files in the unzipped folder for debugging
      run: |
        Get-ChildItem -Path .\unzipped

    - name: Run shiroCheck_win64.exe
      run: |
        ./unzipped/shiroCheck_win64.exe -f ./unzipped/1.txt -fk ./unzipped/shiro_keys.txt -t 30

    - name: Create output directory
      run: |
        mkdir output

    - name: Move results to output folder
      run: |
        move .\unzipped\result_file.txt .\output\

    - name: Zip the output folder
      run: |
        powershell -Command "Compress-Archive -Path .\output\* -DestinationPath output.zip"

    - name: Upload output zip
      uses: actions/upload-artifact@v3
      with:
        name: output-results
        path: output.zip
