name: Build and Install glibc

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential wget

      - name: Download glibc
        run: |
          wget https://ftp.gnu.org/gnu/libc/glibc-2.4.tar.gz
          tar -xzf glibc-2.4.tar.gz
          cd glibc-2.4

      - name: Build glibc
        run: |
          cd glibc-2.4
          mkdir build
          cd build
          ../configure --prefix=/usr/local/glibc-2.4
          make
          sudo make install

      - name: Verify glibc installation
        run: |
          /usr/local/glibc-2.4/bin/ldd --version
