name: Build and Install Dependencies

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build with Docker
        run: |
          echo 'FROM ubuntu:18.04
          RUN apt-get update && \
              apt-get install -y curl unzip git build-essential wget cmake automake libtool autoconf && \
              rm -rf /var/lib/apt/lists/*
          WORKDIR /app
          COPY testformycode.zip .
          RUN unzip testformycode.zip
          WORKDIR /app/testformycode/scripts
          RUN chmod 777 *.sh && ./build_deps.sh
          RUN mkdir /app/testformycode/build && \
              cd /app/testformycode/build && \
              cmake -DXMRIG_DEPS=scripts/deps -DBUILD_SHARED_LIBS=OFF .. && \
              make' > Dockerfile

          docker build -t my-build-image .

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: testformycode/build
