name: Build and Install glibc

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        run: |
          docker pull ubuntu:20.04
          docker run -d --name glibc-builder -v ${{ github.workspace }}:/workspace ubuntu:20.04 tail -f /dev/null

      - name: Install dependencies in Docker
        run: |
          docker exec glibc-builder bash -c "apt-get update && apt-get install -y build-essential wget"

      - name: Download glibc in Docker
        run: |
          docker exec glibc-builder bash -c "wget https://ftp.gnu.org/gnu/libc/glibc-2.4.tar.gz && tar -xzf glibc-2.4.tar.gz -C /workspace"

      - name: Build glibc in Docker
        run: |
          docker exec glibc-builder bash -c "cd /workspace/glibc-2.4 && mkdir build && cd build && ../configure --prefix=/usr/local/glibc-2.4 && make && make install"

      - name: Verify glibc installation in Docker
        run: |
          docker exec glibc-builder bash -c "/usr/local/glibc-2.4/bin/ldd --version"

      - name: Cleanup
        run: |
          docker stop glibc-builder
          docker rm glibc-builder
