name: Setup Docker and Run Command

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag'
        required: false
        default: 'test'  # 默认的标签值

permissions:
  contents: read

jobs:
  long-running-service:
    runs-on: ubuntu-latest

    steps:
      # Checkout your code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up tmate session
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      # Print tmate connection instructions
      - name: Print tmate instructions
        run: |
          echo "To connect to the tmate session, run the following command:"
          echo "ssh $(cat /tmp/tmate-ssh)"
          echo "Alternatively, use the web URL:"
          echo "$(cat /tmp/tmate-url)"

      # Run your long-running service
      - name: Run long service
        run: |
          echo "Starting your long-running service..."
          ./run-your-service.sh  # 替换成你的实际命令
        
