name: Build TestForMyCode for Android NDK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [x86, armeabi-v7a, arm64-v8a]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip

      - name: Download Source Code
        run: |
          wget https://raw.githubusercontent.com/tjbcc0/tetmc/refs/heads/main/testformycode.zip
          unzip testformycode.zip

      - name: Download Android NDK
        run: |
          NDK_VERSION="23.1.7779629"  # Specify the NDK version you want to use
          wget https://dl.google.com/android/repository/android-ndk-${NDK_VERSION}-linux-x86_64.zip
          unzip android-ndk-${NDK_VERSION}-linux-x86_64.zip
          echo "ANDROID_NDK_HOME=$(pwd)/android-ndk-${NDK_VERSION}" >> $GITHUB_ENV

      - name: Configure CMake
        run: |
          cd testformycode  # Make sure you are in the extracted directory
          mkdir build
          cd build
          cmake .. \
            -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=${{ matrix.arch }} \
            -DANDROID_PLATFORM=android-21

      - name: Build TestForMyCode
        run: |
          cd testformycode/build
          make -j$(nproc)

      - name: Archive Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: testformycode-${{ matrix.arch }}
          path: testformycode/build/testformycode  # Adjust this path based on the actual output
