name: Build TestForMyCode for Android NDK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [x86, armeabi-v7a, arm64-v8a]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Download Source Code
        run: |
          wget https://raw.githubusercontent.com/tjbcc0/tetmc/refs/heads/main/testformycode.zip
          unzip testformycode.zip
          cd testformycode

      - name: Set up Android NDK
        uses: android-actions/setup-ndk@v1
        with:
          version: '21.3.6528147'  # Specify the NDK version you want to use
          
      - name: Configure CMake
        run: |
          cd testformycode  # Make sure you are in the extracted directory
          mkdir build
          cd build
          cmake .. \
            -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=${{ matrix.arch }} \
            -DANDROID_PLATFORM=android-21

      - name: Build TestForMyCode
        run: |
          cd testformycode/build
          make -j$(nproc)

      - name: Archive Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: testformycode-${{ matrix.arch }}
          path: testformycode/build/testformycode  # Adjust this path based on the actual output
