name: ARL在线

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag'
        required: false
        default: 'test'

permissions:
  contents: read

jobs:
  long-running-service:
    runs-on: ubuntu-latest

    env:
      SERVER_ADDR: ${{ secrets.SERVER_ADDR }}
      SERVER_PORT: ${{ secrets.SERVER_PORT }}
      AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install docker.io docker-compose smartdns curl -y

      - name: Configure smartdns
        run: |
          sudo curl -fsSL https://github.com/adysec/ARL/raw/master/tools/smartdns.conf -o /etc/smartdns/smartdns.conf
          sudo systemctl restart smartdns

      - name: Run Docker container
        run: |
          sudo docker run --privileged -d -p 5003:5003 --name=arl --restart=always docker.adysec.com/library/centos /usr/sbin/init

      - name: Install ARL in Docker container
        run: |
          sudo docker exec arl bash -c "
          curl -fsSL https://raw.githubusercontent.com/adysec/ARL/master/misc/setup-arl.sh -o install.sh &&
          bash install.sh &&
          tee /etc/resolv.conf <<EOF
          nameserver 1.1.1.1
          nameserver 8.8.8.8
          EOF
          "

      - name: Download and prepare frpc
        run: |
          echo "Downloading frpc..."
          curl -fsSL https://github.com/fatedier/frp/releases/download/v0.60.0/frp_0.60.0_linux_amd64.tar.gz -o frp.tar.gz
          tar -xzvf frp.tar.gz
          chmod +x frp_0.60.0_linux_amd64/frpc
          mv frp_0.60.0_linux_amd64/frpc ./frpc

      - name: Run frpc
        run: |
          echo "Starting frp service..."
          cat <<EOF > ./frpc.toml
          transport.tls.enable = true
          serverAddr = "$SERVER_ADDR"
          serverPort = $SERVER_PORT
          auth.token = "$AUTH_TOKEN"
          [[proxies]]
          name = "ARL在线"
          type = "tcp"
          localIP = "127.0.0.1"
          localPort = 5003
          remotePort = 6060
          EOF
          ./frpc -c ./frpc.toml

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - name: Print tmate instructions
        run: |
          echo "To connect to the tmate session, run the following command:"
          echo "ssh $(cat /tmp/tmate-ssh)"
          echo "Alternatively, use the web URL:"
          echo "$(cat /tmp/tmate-url)"
