name: ARL在线

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag'
        required: false
        default: 'test'  # 默认的标签值

permissions:
  contents: read

jobs:
  long-running-service:
    runs-on: ubuntu-latest

    env:
      SERVER_ADDR: ${{ secrets.SERVER_ADDR }}
      SERVER_PORT: ${{ secrets.SERVER_PORT }}
      AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}

    steps:


      - name: Run long service
        run: |
         ip_address=$(hostname -I)
         sudo apt-get install docker.io docker-compose -y
         sudo apt install smartdns -y
         sudo curl https://github.com/adysec/ARL/raw/master/tools/smartdns.conf > /etc/smartdns/smartdns.conf
         sudo systemctl restart smartdns
         sudo docker run --privileged -it -d -p 5003:5003 --name=arl --restart=always docker.adysec.com/library/centos /usr/sbin/init
         sudo docker exec -it arl bash
          # docker内运行，通过源码安装ARL
         curl https://raw.githubusercontent.com/adysec/ARL/master/misc/setup-arl.sh >install.sh
         bash install.sh
         #docker内运行
         tee /etc/resolv.conf <<"EOF"
         nameserver ip_address
         nameserver 180.76.76.76
         nameserver 4.2.2.1
         nameserver 1.1.1.1
         EOF
         exit

      # Download and prepare frpc
      - name: Download frpc
        run: |
          echo "Downloading frpc..."
          sudo curl -L https://github.com/fatedier/frp/releases/download/v0.60.0/frp_0.60.0_linux_amd64.tar.gz -o frp.tar.gz
          sudo tar -xzvf frp.tar.gz
          sudo mv frp_0.60.0_linux_amd64/frpc ./frpc
          sudo chmod +x ./frpc

      # Run frpc
      - name: Run frpc
        run: |
          echo "Starting your frp service..."
          
          cat <<EOF > ./frpc.toml
          transport.tls.enable = true
          serverAddr = "$SERVER_ADDR"
          serverPort = $SERVER_PORT

          auth.token = "$AUTH_TOKEN"

          [[proxies]]
          name = "ARL在线"
          type = "tcp"
          localIP = "127.0.0.1"
          localPort = 5003
          remotePort = 6060
          EOF

          sudo ./frpc -c ./frpc.toml

          exit
      # Checkout your code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up tmate session
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      # Print tmate connection instructions
      - name: Print tmate instructions
        run: |
          echo "To connect to the tmate session, run the following command:"
          echo "ssh $(cat /tmp/tmate-ssh)"
          echo "Alternatively, use the web URL:"
          echo "$(cat /tmp/tmate-url)"
