name: Build Alist with i386 glibc 2.5

on:
  workflow_dispatch:  # 手动触发
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Use Docker to compile glibc 2.5
      run: |
        docker run --rm -v $(pwd):/workspace -w /workspace i386/debian:buster bash -c "
          apt-get update &&
          apt-get install -y build-essential wget &&
          wget https://ftp.gnu.org/gnu/libc/glibc-2.5.tar.gz &&
          tar -xzf glibc-2.5.tar.gz &&
          mkdir glibc-2.5/build &&
          cd glibc-2.5/build &&
          ../configure --prefix=/opt/glibc-2.5 --host=i686-pc-linux-gnu --enable-add-ons &&
          make -j$(nproc) &&
          make install &&
          export LD_LIBRARY_PATH=/opt/glibc-2.5/lib:$LD_LIBRARY_PATH &&
          cd ../../ &&
          GOARCH=386 go build -o alist
        "

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: alist-i386
        path: ./alist
      uses: actions/upload-artifact@v3
      with:
        name: alist-i386
        path: ./alist
