name: Build Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          cat <<EOF > Dockerfile
          FROM debian:stretch

          RUN apt-get update && apt-get install -y \\
              wget \\
              gnupg \\
              curl \\
              && rm -rf /var/lib/apt/lists/*

          RUN wget -O /tmp/kali-linux-mini-2016.1-amd64.iso https://old.kali.org/kali-images/kali-2016.1/kali-linux-mini-2016.1-amd64.iso

          CMD ["bash"]
          EOF

          # 构建 Docker 镜像
          docker build -t kali-linux-mini .

      - name: Run Docker container
        run: |
          # 运行 Docker 容器
          docker run --name kali-container -d kali-linux-mini
          # 可以在这里添加其他操作，比如在容器中执行命令
          docker exec kali-container bash -c "echo 'Kali Linux Mini container is running!'"

      - name: Stop and remove container
        run: |
          # 停止并删除容器
          docker stop kali-container
          docker rm kali-container
