name: Build with Debian 7

on:
  push:
    branches:
      - master
  workflow_dispatch:  # 支持手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 设置 Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 创建 Dockerfile
      - name: Create Dockerfile
        run: |
          cat <<EOF > Dockerfile
          FROM debian:7

          # 更新源并安装必要工具
          RUN echo "deb http://archive.debian.org/debian wheezy main" > /etc/apt/sources.list && \
              echo "deb http://archive.debian.org/debian-security wheezy/updates main" >> /etc/apt/sources.list && \
              echo "Acquire::Check-Valid-Until false;" >> /etc/apt/apt.conf.d/99ignore-valid-until && \
              apt-get update && \
              apt-get install -y --no-install-recommends \
              build-essential \
              cmake \
              automake \
              libtool \
              autoconf \
              wget \
              git \
              curl --allow-unauthenticated && \
              apt-get clean

          # 手动安装 libstdc++ 和 libgcc
          RUN wget http://archive.debian.org/debian/pool/main/g/gcc-4.7/libstdc++6-4.7-dev_4.7.2-5_amd64.deb && \
              wget http://archive.debian.org/debian/pool/main/g/gcc-4.7/libgcc1_4.7.2-5_amd64.deb && \
              dpkg -i libstdc++6-4.7-dev_4.7.2-5_amd64.deb && \
              dpkg -i libgcc1_4.7.2-5_amd64.deb && \
              rm *.deb

          # 锁定 glibc，防止升级
          RUN apt-mark hold libc6 libc-bin

          # 设置工作目录并复制代码
          WORKDIR /app
          COPY . .

          # 构建项目
          RUN make
          EOF

      # 构建 Docker 镜像
      - name: Build Docker image for Debian 7
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: false  # 不推送到 Docker Hub
          tags: debian7-build:latest

      # 运行构建命令
      - name: Run build inside Docker
        run: |
          docker run --rm debian7-build:latest /bin/bash -c "make all"
