name: Build Docker Image from ISO

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up QEMU and required packages
      run: |
        sudo apt-get update
        sudo apt-get install -y wget genisoimage

    - name: Create Dockerfile
      run: |
        cat <<EOF > Dockerfile
        FROM debian:bullseye

        RUN apt-get update && apt-get install -y \\
            wget \\
            genisoimage \\
            && rm -rf /var/lib/apt/lists/*

        RUN wget -O /tmp/kali-linux-mini.iso https://old.kali.org/kali-images/kali-2016.1/kali-linux-mini-2016.1-amd64.iso

        RUN mkdir -p /usr/local/kali

        # Use isoinfo to extract files from the ISO
        RUN mkdir /usr/local/kali/extracted && \\
            isoinfo -l -i /tmp/kali-linux-mini.iso > /usr/local/kali/filelist.txt && \\
            for file in \$(isoinfo -x / -i /tmp/kali-linux-mini.iso | awk '{ print \$2 }'); do \\
                isoinfo -x \$file -i /tmp/kali-linux-mini.iso > /usr/local/kali/extracted/\$file; \\
            done

        # Clean up ISO file
        RUN rm /tmp/kali-linux-mini.iso

        CMD ["bash"]
        EOF
      shell: bash

    - name: Build Docker image
      run: docker build -t kali-docker .

    - name: Run Docker container
      run: docker run --name kali_container -d kali-docker

    - name: Clean up
      run: docker rm -f kali_container
