name: Build Docker Image from ISO

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up QEMU
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-utils genisoimage

    - name: Create Dockerfile
      run: |
        cat <<EOF > Dockerfile
        FROM debian:bullseye

        RUN apt-get update && apt-get install -y \\
            wget \\
            qemu-utils \\
            genisoimage \\
            && rm -rf /var/lib/apt/lists/*

        RUN wget -O /tmp/kali-linux-mini.iso https://old.kali.org/kali-images/kali-2016.1/kali-linux-mini-2016.1-amd64.iso

        RUN mkdir /mnt/kali

        RUN mount -o loop /tmp/kali-linux-mini.iso /mnt/kali

        RUN cp -r /mnt/kali/* /usr/local/

        RUN umount /mnt/kali && rm /tmp/kali-linux-mini.iso

        CMD ["bash"]
        EOF
      shell: bash

    - name: Build Docker image
      run: docker build -t kali-docker .

    - name: Run Docker container
      run: docker run --name kali_container -d kali-docker

    - name: Clean up
      run: docker rm -f kali_container
