name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Dockerfile
        run: |
          cat <<EOF > Dockerfile
          FROM kalilinux/kali-rolling

          RUN apt-get update && apt-get install -y \
              curl \
              wget \
              unzip \
              git \
              build-essential \
              cmake \
              automake \
              libtool \
              autoconf \
              glibc-source \
              libstdc++-14-dev \
              libgcc-12-dev && \
              apt-get clean
          EOF

      - name: Build Docker Image
        run: |
          docker build -t my-kali-build-env .

      - name: Verify Docker Image
        run: |
          docker images
