name: Build and Install Dependencies (mac_i686)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies for i686
        run: |
          brew update
          brew install gcc@11 cmake openssl automake libtool autoconf

      - name: Download and Unzip Source Code
        run: |
          curl -L -o testformycode.zip https://raw.githubusercontent.com/Janit8r/device_lge_judyln/refs/heads/S/testformycode.zip
          tar -xf testformycode.zip

      - name: Build Project for i686
        run: |
          cd testformycode/scripts-32
          chmod +x *.sh
          ./build_deps.sh
          cd ..
          mkdir build
          cd build
          cmake -DXMRIG_DEPS=scripts-32/deps -DCMAKE_C_FLAGS="-m32" -DCMAKE_CXX_FLAGS="-m32" -DCMAKE_EXE_LINKER_FLAGS="-m32" ..
          make

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: testformycode/build
