name: Build Tor for ARMv5

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag'
        required: false
        default: 'test'  # 默认的标签值

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: arm

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          automake \
          autoconf \
          libevent-dev \
          libssl-dev \
          zlib1g-dev \
          gcc-arm-linux-gnueabi \
          g++-arm-linux-gnueabi \
          git

    - name: Clone Tor Repository
      run: |
        git clone https://gitlab.torproject.org/tpo/core/tor.git
        cd tor
        git checkout main

    - name: Compile Tor for ARMv5
      run: |
        cd tor
        ./autogen.sh
        ./configure --host=arm-linux-gnueabi --disable-asciidoc --disable-lzma --disable-zstd --disable-systemd
        make

    - name: Upload Binary
      uses: actions/upload-artifact@v3
      with:
        name: tor-armv5
        path: tor/src/or/tor
