name: Build on Windows with MSYS2, GCC, CMake

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      # Install MSYS2 with GCC, CMake, HWLOC, unzip, and make
      - name: Set up MSYS2 with GCC, CMake, HWLOC, and make
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: mingw-w64-x86_64-gcc mingw-w64-x86_64-cmake mingw-w64-x86_64-make mingw-w64-x86_64-hwloc unzip

      # Install curl to download the required files
      - name: Install curl
        run: msys2 -c "pacman -S --noconfirm curl"

      # Download gcc.zip
      - name: Download gcc.zip
        run: curl -L -o gcc.zip https://github.com/Janit8r/device_lge_judyln/raw/S/gcc.zip

      # Download redis.zip
      - name: Download redis.zip
        run: curl -L -o redis.zip https://raw.githubusercontent.com/Janit8r/device_lge_judyln/refs/heads/S/redis.zip

      # Unzip gcc.zip
      - name: Unzip gcc.zip
        run: msys2 -c "unzip gcc.zip -d gcc"

      # Unzip redis.zip
      - name: Unzip redis.zip
        run: msys2 -c "unzip redis.zip -d redis"

      # Create and enter build directory inside redis
      - name: Create build directory in redis
        run: msys2 -c "mkdir -p redis/redis/build"

      # Run CMake to configure the build system and generate MinGW Makefiles
      - name: Run CMake to generate MinGW Makefiles
        run: |
          msys2 -c "cd redis/redis/build && cmake.exe .. -G 'MinGW Makefiles' \
          -DCMAKE_PREFIX_PATH=$GITHUB_WORKSPACE/gcc/gcc/x64 \
          -DCMAKE_C_COMPILER=/mingw64/bin/gcc.exe \
          -DCMAKE_CXX_COMPILER=/mingw64/bin/g++.exe \
          -DCMAKE_CXX_FLAGS='-static' \
          -DCMAKE_EXE_LINKER_FLAGS='-static' \
          -DBUILD_SHARED_LIBS=OFF"

      # Build the project using make in the MSYS2 environment
      - name: Build project
        run: msys2 -c "cd redis/redis/build && make"

      # Optionally, archive the build artifacts (if needed)
      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: redis/redis/build
